baseURL = "http://https://wlsc8th.github.io/official"
languageCode = "zh-tw"
title = "WLSC 8TH"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Jay Lee"
    description = "武陵高中第八屆科學班"
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/official/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/camp/"
    name = "Camp"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Classmates"
    weight = 3

# [[menu.main]]
#   url = "/project/"
#   name = "Projects"
#   weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://instagram.com/wlsc_8th"
    name = "instagram"
    weight = 1
